default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USER_NAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: project_management_development

test:
  <<: *default
  database: project_management_test

production:
  <<: *default
  database: project_management_production
  username: project_management
  password: <%= ENV["PROJECT_MANAGEMENT_DATABASE_PASSWORD"] %>
